import random

QUOTES = [
    "“Journaling is like whispering to one’s self and listening at the same time.” – Mina Murray",
    "“Fill your paper with the breathings of your heart.” – William Wordsworth",
    "“In the journal I do not just express myself freely; I create myself.” – Susan Sontag",
    "“Preserve your memories, keep them well, what you forget you can never regain.” – Louisa May Alcott",
    "“Keep a diary, and someday it will keep you.” – Mae West",
    "“I can shake off everything as I write; my sorrows disappear, my courage is reborn.” – Anne Frank",
    "“Paper has more patience than people.” – Anne Frank",
    "“Documenting little things of your everyday life means honoring them.” – Bonnie Gillespie",
    "“Writing in a journal reminds you of your commitment to the time you spent.” – Jim Rohn",
    "“The acts of writing and reading are personal, quiet, and introspective.” – Jhumpa Lahiri",
    "“I write because I don’t know what I think until I read what I say.” – Flannery O’Connor",
    "“Your journal is a mirror to your soul. Look into it without fear.”",
    "“Start writing, no matter what. The water does not flow until the faucet is turned on.” – Louis L'Amour",
    "“A journal is your completely private space to think out loud.”",
    "“Write what should not be forgotten.” – Isabel Allende",
    "“Whether you keep a journal or not, your life is being recorded in memory.”",
    "“A personal journal is an uninterrupted conversation with your inner voice.”",
    "“To write is to carve a quiet space out of the noise of the world.”",
    "“Journaling is paying attention to the context of your life.”",
    "“Ideas are like fish. If you want to catch little fish, you can stay in the shallow water. But if you want to catch the big fish, you’ve got to go deeper.” – David Lynch",
    "“The unexamined life is not worth living.” – Socrates",
    "“Knowing yourself is the beginning of all wisdom.” – Aristotle",
    "“Who looks outside, dreams; who looks inside, awakes.” – Carl Jung",
    "“Your vision will become clear only when you can look into your own heart.” – Carl Jung",
    "“Quiet minds cannot be perplexed or frightened, but go on at their own private pace.” – Ralph Waldo Emerson",
    "“What a wonderful thought it is that some of the best days of our lives haven't happened yet.”",
    "“The starting point of discovering who you are is being comfortable with yourself.” – Robin Sharma",
    "“Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.” – Marcus Aurelius",
    "“You have power over your mind — not outside events. Realize this, and you will find strength.” – Marcus Aurelius",
    "“Life can only be understood backwards; but it must be lived forwards.” – Søren Kierkegaard",
    "“Turn your wounds into wisdom.” – Oprah Winfrey",
    "“The journey into self-discovery requires stepping into the quiet.”",
    "“Do not ask what the world needs. Ask what makes you come alive, and go do it.” – Howard Thurman",
    "“In the middle of difficulty lies opportunity.” – Albert Einstein",
    "“Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.” – Rumi",
    "“The soul usually knows what to do to heal itself. The challenge is to silence the mind.” – Caroline Myss",
    "“Be subject to your own intuition.”",
    "“Honesty with yourself is the highest form of self-respect.”",
    "“Every day provides a fresh page to write a new story.”",
    "“You are the author of your own story. Make it worth reading.”",
    "“Silence is a source of great strength.” – Lao Tzu",
    "“Within you, there is a stillness and a sanctuary to which you can retreat at any time.” – Hermann Hesse",
    "“Peace comes from within. Do not seek it without.” – Buddha",
    "“Mindfulness is a way of befriending ourselves and our experience.” – Jon Kabat-Zinn",
    "“Slow down and everything you are chasing will come around and catch you.” – John De Paola",
    "“Almost everything will work again if you unplug it for a few minutes, including you.” – Anne Lamott",
    "“Tension is who you think you should be. Relaxation is who you are.” – Chinese Proverb",
    "“Nurture your mind with great thoughts, for you will never go any higher than you think.” – Benjamin Disraeli",
    "“Breath is the bridge which connects life to consciousness.” – Thich Nhat Hanh",
    "“Smile, breathe, and go slowly.” – Thich Nhat Hanh",
    "“The present moment is filled with joy and happiness. If you are attentive, you will see it.” – Thich Nhat Hanh",
    "“Rule your mind or it will rule you.” – Horace",
    "“To inhabit the present moment is to anchor yourself in clarity.”",
    "“Let your mind be like water: quiet, adaptable, and deep.”",
    "“Softness is not weakness; it is the ultimate strength of depth.”",
    "“Clarity comes when you allow the dust of the day to settle.”",
    "“In quietness and confidence shall be your strength.”",
    "“Countless small moments make up a remarkable life.”",
    "“Give yourself permission to pause.”",
    "“Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.” – Wayne Dyer",
    "“Time you enjoy wasting is not wasted time.” – Bertrand Russell",
    "“Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.” – Buddha",
    "“We do not remember days, we remember moments.” – Cesare Pavese",
    "“Memory is the diary that we all carry about with us.” – Oscar Wilde",
    "“Every moment is a fresh beginning.” – T.S. Eliot",
    "“What lies behind us and what lies before us are tiny matters compared to what lies within us.” – Ralph Waldo Emerson",
    "“Be not afraid of growing slowly; be afraid only of standing still.” – Chinese Proverb",
    "“Growth begins at the end of your comfort zone.”",
    "“Small daily improvements over time lead to stunning results.” – Robin Sharma",
    "“Do something today that your future self will thank you for.”",
    "“You don’t have to see the whole staircase, just take the first step.” – Martin Luther King Jr.",
    "“The best time to plant a tree was 20 years ago. The second best time is now.”",
    "“Act as if what you do makes a difference. It does.” – William James",
    "“Change the way you look at things and the things you look at change.” – Wayne Dyer",
    "“The only journey is the one within.” – Rainer Maria Rilke",
    "“Your life is a canvas; write each line with care.”",
    "“Every sunset brings the promise of a new dawn.”",
    "“Nothing is permanent in this wicked world — not even our troubles.” – Charlie Chaplin",
    "“The power for creating a better future is contained in the present moment.” – Eckhart Tolle",
    "“Realize deeply that the present moment is all you have.” – Eckhart Tolle",
    "“Creativity is intelligence having fun.” – Albert Einstein",
    "“The chief enemy of creativity is ‘good’ sense.” – Pablo Picasso",
    "“You can’t use up creativity. The more you use, the more you have.” – Maya Angelou",
    "“Make visible what, without you, might perhaps never have been seen.” – Robert Bresson",
    "“Art enables us to find ourselves and lose ourselves at the same time.” – Thomas Merton",
    "“Trust the quiet work happening under the surface.”",
    "“Your thoughts shape your reality. Choose ones that build you up.”",
    "“In the depth of winter, I finally learned that within me there lay an invincible summer.” – Albert Camus",
    "“Everything in life is writable about if you have the outgoing guts to do it.” – Sylvia Plath",
    "“Expressing your truth is an act of courage.”",
    "“The secret of getting ahead is getting started.” – Mark Twain",
    "“Believe you can and you're halfway there.” – Theodore Roosevelt",
    "“Keep your face always toward the sunshine — and shadows will fall behind you.” – Walt Whitman",
    "“Hope is a waking dream.” – Aristotle",
    "“Happiness is not something ready-made. It comes from your own actions.” – Dalai Lama",
    "“To love oneself is the beginning of a lifelong romance.” – Oscar Wilde",
    "“Wherever you go, go with all your heart.” – Confucius",
    "“The future belongs to those who believe in the beauty of their dreams.” – Eleanor Roosevelt",
    "“ECHOES will reflect back whatever truth you whisper into it.”",
    "“Every entry is a mirror for tomorrow’s you.”"
]

def get_daily_quote() -> str:
    """Returns a random quote from the curated ECHOES library."""
    return random.choice(QUOTES)